# Generated by Django 4.1 on 2022-09-27 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
